name: "GroupAlarm HomeAssistant"
slug: "groupalarm_homeassistant"
version: "1.0.18"
description: "Bindet GroupAlarm in Home Assistant ein."
arch: [amd64, aarch64]


init: false         
startup: application  

boot: auto
ingress: true
ingress_stream: true
ingress_port: 8099  
panel_icon: mdi:alarm-light
panel_title: GroupAlarm
services: [mqtt:need]
map:
  - config:rw
options:
  api_base_url: "https://app.groupalarm.com/api/v1"
  token: ""               
  user_id: 0               
  poll_interval_sec: 30
  discovery_prefix: "homeassistant"
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  device_name: "GroupAlarm Bridge"
  device_id: "groupalarm_bridge_1"
  verify_tls: true

schema:
  api_base_url: str?
  token_type: list(personal|api)?
  token: str
  user_id: int
  poll_interval_sec: int?
  discovery_prefix: str?
  device_name: str?
  device_id: str?
  verify_tls: bool?
  default_tag_id: int?                  
  default_event_external_id: str?        
  mqtt_host: str?                         
  mqtt_port: int?                        
  mqtt_username: str?
  mqtt_password: str?

